export const appRegistry = [
  // 核心
  { id: 'chat', name: 'app_sidebar_chat', icon: '💬', iconClass: 'icon-chat',
    load: () => import('./apps/chat/index.vue'),
    mobileLoad: () => import('./apps/chat/MobileChatView.vue'),
    sideChat: false,
    defaultSize: { w: 900, h: 640 } },
  { id: 'tasks', name: 'app_sidebar_tasks', icon: '✅', iconClass: 'icon-tasks',
    load: () => import('./apps/tasks/index.vue'), defaultSize: { w: 700, h: 500 } },
  { id: 'files', name: 'app_sidebar_files', icon: '📁', iconClass: 'icon-files',
    load: () => import('./apps/files/index.vue'), defaultSize: { w: 750, h: 520 } },
  // 应用
  { id: 'notebook', name: 'app_sidebar_notebook', icon: '📓', iconClass: 'icon-notebook',
    load: () => import('./apps/notebook/index.vue'), defaultSize: { w: 850, h: 600 } },
  { id: 'finance', name: 'app_sidebar_finance', icon: '💰', iconClass: 'icon-finance',
    load: () => import('./apps/finance/index.vue'), defaultSize: { w: 800, h: 560 } },
  { id: 'subscriber', name: 'app_sidebar_subscriber', icon: '📻', iconClass: 'icon-subscriber',
    load: () => import('./apps/subscriber/index.vue'), defaultSize: { w: 800, h: 560 } },
  { id: 'cryptobot', name: 'app_sidebar_cryptobot', icon: '📈', iconClass: 'icon-cryptobot',
    load: () => import('./apps/cryptobot/index.vue'), defaultSize: { w: 900, h: 600 } },
  { id: 'reader', name: 'app_sidebar_reader', icon: '📖', iconClass: 'icon-reader',
    load: () => import('./apps/reader/index.vue'), defaultSize: { w: 800, h: 600 } },
  { id: 'poker', name: 'app_sidebar_poker', icon: '🃏', iconClass: 'icon-poker',
    load: () => import('./apps/poker/index.vue'), defaultSize: { w: 900, h: 700 } },
  { id: 'fortune', name: 'app_sidebar_fortune', icon: '🔮', iconClass: 'icon-fortune',
    load: () => import('./apps/fortune/index.vue'), defaultSize: { w: 700, h: 560 } },
  { id: 'banana', name: 'app_sidebar_banana', icon: '📱', iconClass: 'icon-banana',
    load: () => import('./apps/banana/index.vue'), defaultSize: { w: 420, h: 700 } },
  { id: 'openclaw', name: 'app_sidebar_openclaw', icon: '🦞', iconClass: 'icon-openclaw',
    load: () => import('./apps/openclaw/index.vue'), defaultSize: { w: 520, h: 700 } },
  // 工具
  { id: 'settings', name: 'app_sidebar_settings', icon: '⚙️', iconClass: 'icon-settings',
    load: () => import('./apps/settings/index.vue'), defaultSize: { w: 750, h: 520 } },
  { id: 'create-app', name: 'app_sidebar_create_app', icon: '➕', iconClass: 'icon-create',
    load: () => import('./apps/createapp/index.vue'), defaultSize: { w: 700, h: 500 } },
  // 隐藏（不在桌面显示，程序内导航打开）
  { id: 'task-detail', name: 'app_sidebar_tasks', icon: '✅', iconClass: 'icon-tasks',
    load: () => import('./apps/tasks/detail.vue'), hidden: true, defaultSize: { w: 800, h: 560 } },
  { id: 'task-create', name: 'app_sidebar_tasks', icon: '✅', iconClass: 'icon-tasks',
    load: () => import('./apps/tasks/create.vue'), hidden: true, defaultSize: { w: 700, h: 500 } },
];
