const codingAgents = () => {
  return [
    "",
    "## Coding Agents Apps",
    "",
    "AIOS includes two apps for local coding-agent CLIs: `claude-code` and `codex`. Both are served by the apps service with these API prefixes:",
    "",
    "- `/apps/claude-code/*`",
    "- `/apps/codex/*`",
    "",
    "### Availability And Status",
    "",
    "- Do not guess whether these apps are currently available.",
    "- First call `GET /apps/claude-code/status` or `GET /apps/codex/status` to check status.",
    "- These status endpoints return at least `installed`, and usually also `version` and `cliPath`.",
    "- Only when `installed === true` should you present them as available or call their chat APIs.",
    "",
    "### Typical Call Order",
    "",
    "When the user wants to chat with Claude Code / Codex, view sessions, or continue a session, use this order:",
    "",
    "1. `GET /apps/<app>/status` to check installation",
    "2. `GET /apps/<app>/conversations` to get the conversation list",
    "3. To create a new conversation, call `POST /apps/<app>/conversations/create`",
    "4. To read history, call `GET /apps/<app>/messages?conversationId=<id>`",
    "5. To send a message, call `POST /apps/<app>/send`",
    "",
    "`<app>` must be either `claude-code` or `codex`.",
    "",
    "### Chat Send Endpoints",
    "",
    "- `POST /apps/claude-code/send`",
    "- `POST /apps/codex/send`",
    "",
    "The request body is JSON and must include at least:",
    "",
    "```json",
    "{",
    '  "conversationId": "<session-id>",',
    '  "message": "..."',
    "}",
    "```",
    "",
    "The response is an `application/x-ndjson` stream. Each line is one JSON event. Common types:",
    "",
    '- `{ "type": "event", "payload": ... }`',
    '- `{ "type": "done" }`',
    '- `{ "type": "error", "message": "..." }`',
    "",
    "### Response Rules",
    "",
    "- If the user asks whether Claude Code / Codex is available, check the corresponding `status` endpoint before answering.",
    "- If the user asks whether it can be called, first confirm `installed`, then explain the endpoint.",
    "- If the user asks you to integrate, debug, or fix these apps, you may directly modify:",
    "  - `server/apps/claude-code/`",
    "  - `server/apps/codex/`",
    "  - `gui/src/apps/claude-code/`",
    "  - `gui/src/apps/codex/`",
    "- Chat conversations and messages for these apps should be persisted in the app database, not only in temporary frontend state."
  ].join("\n");
};

export {
  codingAgents
};
