services:
  aios:
    build:
      context: ../../
      dockerfile: doc/docker/Dockerfile
    ports:
      - "9500:9500"
    volumes:
      - ../../database:/app/database
      - ../../files:/app/files
    restart: unless-stopped
