services:
  aios:
    build:
      context: ../../
      dockerfile: doc/docker/Dockerfile
    ports:
      - "9500:9500"
    volumes:
      - aios_database:/app/database
      - aios_files:/app/files
    restart: unless-stopped

volumes:
  aios_database:
  aios_files:
